## Matrix inversion is usually a costly computation. If the resultant inverted
## mattrix is expected to be used in a series of calucations, caching the 
## value of the inverse will save computational resources.
##

## Function makeCacheMatrix is used to define a list of functions that will allow
## the inverse of a matrix passed to the function to be calculated.
##
makeCacheMatrix <- function(x = matrix()) {
    ## The first test is to make sure that the parameter passed to the function is
    ## a matrix. If the parameter passed is not a matrix, stop execution of the
    ## function.
    ##
    if (!is.matrix(x)){
        stop("The parameter passed to the function is not a matix.")
    }    

    ## The second test is to verify that the matrix passed to the function is a 
    ## square matrix. The number of rows does not equal the number of columns in the
    ## matrix passed to the function, stop execution of the function.
    ##
    x_rows <-nrow(x)
    x_cols <-ncol(x)
    if (x_rows != x_cols){
        stop("The matrix passed to the function is not a square matrix")
    }
  
    ## At this point in the function, the parameter passed has been verified as a
    ## square matrix. The next step is to define the functions necessary to 
    ## calcuatate the inverse of the matrix.
    
    ## Set the value of the inverted matrix to null
    inverted_matrix <<- NULL
     
    ## Define the set function to assign the intial value of the matrix
    ## and re-initialize the value of the inverted_matrix. 
    set <- function(y) {
        x <<- y 
        inverted_matrix <<- NULL 
    }
    
    ## Define the get function to return the value of the matrix.
    get <- function() x 
    
    ## Define the setinverse function to assign the calculated
    ## inverse of the matrix.
    setinverse <- function(inverse) inverted_matrix <<- inverse

    ## Define the getinverse function to return the value of the 
    ## inverted_matrix.
    getinverse <- function() inverted_matrix 
    
    ## Create a list of containg the functions defined above.
    ##
    list(set = set, 
         get = get,
         setinverse = setinverse, 
         getinverse = getinverse)

}



## Function cacheSolve attempts to compute the inverse of the matrix created  
## by the makeCacheMatrix. The function first checks to see if the inverse has
## already been calculated and stored. If the inverse is already stored in the cache,
## return the cached inverse, otherwise proceed to calculate the inverse.

cacheSolve <- function(x, ...) {
    ## The paramater x passed to the function is the matrix generated by the 
    ## makeCacheMatrix function.
  
    ## First assign the local variable inverted_matrix the value of the cached
    ## inverse matrix.
    inverted_matrix <- x$getinverse()
  
    ## Test the value of the cached matrix to determine if it has already been
    ## calcualted. If the inverse has already been calcualted, return the cached
    ## data and exist the function.
    ##
    if (!is.null(inverted_matrix)){
        message("getting cached data")
        return(inverted_matrix)
    }
 
    ## At this point, the inverse of the marix does not exist and needs to be
    ## calcualted.
    
    ## First step is to assing the local variable matrix.data the value of
    ## matrix x.
    #
    matrix.data = x$get()
    
    ## The next step is to calcualte the inverse of the matrix using the sovle
    ## function and assigning the result to the local varialbe inverted_matrix.
    ##
    inverted_matrix <- solve(matrix.data, ...)

    ## Assign the value of the calculated inverse to the cache via the setinv
    ## function.
    ##
    x$setinv(inverted_matrix)
  
    ## Return the value of calculated inverse.
    ##
    return(inverted_matrix)
    
}
